import ModalLogic.PropositionalLogic.DeductionSystem.Notations
import ModalLogic.PropositionalLogic.DeductionSystem.Minimal0
import ModalLogic.PropositionalLogic.DeductionSystem.Minimal
import ModalLogic.PropositionalLogic.DeductionSystem.Intuitional
import ModalLogic.PropositionalLogic.DeductionSystem.Classical